SLCeleb_tamil:
  name: "SLCeleb_tamil"
  _target_: src.datasets.VoxCeleb
  dir_name: '/home/stefan/Documents/CourseWork/SLCeleb/Tamil/test'
  instance_transforms: ${transforms.instance_transforms.inference}
  sample_rate: 16000
  extension: 'wav'