train:
  name: "VoxCeleb2"
  _target_: src.datasets.VoxCeleb
  dir_name: '/home/stankuznetsov/CourseWork/vox2_3000_pref'
#  dir_name: '/home/stefan/Documents/CourseWork/VoxCeleb/vox2_dev1/aac'
  instance_transforms: ${transforms.instance_transforms.train}
  sample_rate: 16000
  extension: 'm4a'