voxceleb2:
  _target_: src.datasets.VoxCeleb
  dir_name: '/home/stefan/Documents/CourseWork/VoxCeleb/TODO'
  instance_transforms: ${transforms.instance_transforms.train}
  sample_rate: 16000
  max_duration: 40
  celeb_id: 2
  extension: '.m4a'