train:
  name: "VoxCeleb2"
  _target_: src.datasets.VoxCeleb
  dir_name: '/home/stefan/Documents/CourseWork/VoxCeleb/vox2_dev2/aac'
  instance_transforms: ${transforms.instance_transforms.train}
  sample_rate: 16000
  max_duration: 15
  extension: 'm4a'