Zulu:
  name: "Zulu"
  _target_: src.datasets.VoxCeleb
  dir_name: '/home/stefan/Documents/CourseWork/ZULU/audio'
  instance_transforms: ${transforms.instance_transforms.inference}
  sample_rate: 16000
  extension: 'wav'