device: "auto"
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.EERMetric
    device: ${metrics.device}
    name: "Zulu"
    pairs_path: "/home/stefan/Documents/CourseWork/VoxCeleb/data/trials/test_split_zulu.txt"