train:
  data_object: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.MUSANAugment
        musan_path: "/home/stankuznetsov/CourseWork/MUSAN/musan"
#        musan_path: "/home/stefan/Documents/CourseWork/MUSAN/musan"
inference:
  data_object: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially