_target_: src.model.Wav2vecBert2Adapter
layers: [11, 12, 13, 14, 15, 16, 17]
emb_dim: 512
freeze_strategy: 'none'
#pretrained: '/home/stefan/Documents/CourseWork/pretrained/'
pretrained: '/home/stankuznetsov/CourseWork/Wav2Vec_bert_2/'