_target_: src.model.XeusASVAdapter
pretrain: '/home/stankuznetsov/CourseWork/XEUS/model/xeus_checkpoint.pth'
#pretrain: '/home/stefan/Documents/CourseWork/XEUS/model/xeus_checkpoint.pth'
layers: [3, 9, 10, 11, 12, 16]
#layers: [1]
emb_dim: 1024