_target_: src.model.Xeus
pretrain: '/home/stankuznetsov/CourseWork/XEUS/model/xeus_checkpoint.pth'
#pretrain: '/home/stefan/Documents/CourseWork/XEUS/model/xeus_checkpoint.pth'
layers: [0, 9, 18]
emb_dim: 1024