_target_: src.model.XeusFineTunning
#pretrain: '/home/stankuznetsov/CourseWork/XEUS/model/xeus_checkpoint.pth'
pretrain: '/home/stefan/Documents/CourseWork/XEUS/model/xeus_checkpoint.pth'
layers: [5, 6, 7, 8, 9, 10]
emb_dim: 512
freeze_strategy: 'all'