defaults:
  - model: xeus_fine-tunning_home
  - datasets: VoxCeleb1 # we do not want to run inference on training data
  - dataloader: VoxCeleb_xeus
  - transforms: transforms_xeus_home
  - metrics: voxceleb_metrics_home
  - _self_
inferencer:
  device_tensors: ["data_object", "labels", 'lengths'] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "xeus_emb_cache" # any name here, can be a dataset name
  seed: 1
  skip_model_load: False
  from_pretrained: null # path to the pretrained model
