defaults:
  - model: xeus_fine-tunning_home
  - datasets: VoxCeleb1 # we do not want to run inference on training data
  - dataloader: VoxCeleb_xeus
  - transforms: transforms_xeus_home
  - metrics: voxceleb_metrics_home
  - _self_
loss_function:
  _target_: src.loss.AAMSoftmaxLoss
  embed_dim: 256
  num_classes: 5994
inferencer:
  device_tensors: ["data_object", "labels", 'lengths'] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "xeus_emb_cache_vox1_adapter" # any name here, can be a dataset name
  seed: 1
  skip_model_load: False
  from_pretrained: "/home/stefan/Documents/CourseWork/data/saved/train_adapter_xeus_fixed/xeus_adapter_checkpoint.pth" # path to the pretrained model
