defaults:
  - model: wav2vec_bert_2_base.yaml
  - writer: wandb
  - metrics: voxceleb_metrics
  - datasets:
    - VoxCeleb2
    - VoxCeleb1_test
  - dataloader: VoxCeleb
  - transforms: transforms_v1
  - _self_
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-3
  weight_decay: 2e-5
lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  eta_min: 1e-4
loss_function:
  _target_: src.loss.AAMSoftmaxLoss
  embed_dim: 512
  num_classes: 5994
trainer:
  log_step: 100
  log_audio: False
  n_epochs: 5
  device_tensors: ["data_object", "labels", "lengths"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "off" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 1 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "data/saved"
  seed: 1
  use_amp_autocast: False
