from src.transforms.instance_transforms import AudioSizeNormalize
from src.transforms.instance_transforms import RandomCrop1D
from src.transforms.instance_transforms import AdaptiveCrop1D
from src.transforms.augment import MUSANAugment