train:
  data_object: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.AudioSizeNormalize
      - _target_: src.transforms.RandomCrop1D
        min_sec: 5
        max_sec: 5
        sample_rate: 16000

inference:
  data_object: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.AudioSizeNormalize
      - _target_: src.transforms.RandomCrop1D
        min_sec: 5
        max_sec: 5
        sample_rate: 16000
