train:
  data_object: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.AudioNormalize
      - _target_: src.transforms.AdaptiveCrop1D
        min_sec: 5
        max_sec: 7
        sample_rate: 16000

inference:
  data_object: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.AudioNormalize
      - _target_: src.transforms.AdaptiveCrop1D
        min_sec: 5
        max_sec: 20
        sample_rate: 16000
